task:
    resource: '../src/Care/Infrastructure/Controller/'
    type: attribute
    prefix: '/api/tasks'
    trailing_slash_on_root: false

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger.json:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
